# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='fornavn')),
                ('last_name', models.CharField(max_length=50, verbose_name='etternavn')),
                ('phone', models.CharField(max_length=20, verbose_name='mobilnummer')),
                ('number_of_entries', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='e-post')),
                ('about_me', models.TextField(blank=True, default='', verbose_name='litt om meg selv')),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest_book.Member'),
        ),
        migrations.AddField(
            model_name='entry',
            name='members_involved',
            field=models.ManyToManyField(blank=True, related_name='members_involved', to='guest_book.Member'),
        ),
    ]
