# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='e-post'),
        ),
    ]
