# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0002_member_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.AlterField(
            model_name='entry',
            name='members_involved',
            field=models.ManyToManyField(blank=True, related_name='involved_entries', to='guest_book.Member'),
        ),
    ]
