# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0004_auto_20180321_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 12, 44, 27, 209646, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
