# Generated by Django 2.0.3 on 2018-03-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0009_auto_20180327_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='e-post'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='hansen', max_length=50, verbose_name='etternavn'),
            preserve_default=False,
        ),
    ]
