# Generated by Django 2.0.3 on 2018-03-28 09:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0010_auto_20180327_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest_book.Member', verbose_name='forfatter'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='bilde'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='members_involved',
            field=models.ManyToManyField(blank=True, related_name='involved_entries', to='guest_book.Member', verbose_name='medlemmer med'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='dato publisert'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(verbose_name='tekst'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=255, verbose_name='tittel'),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fødselsdato'),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='profilbilde'),
        ),
    ]
